version: '2'
networks:
  default:
    external:
      name: nginx-proxy
  dbpsql-tier:
    external:
     name: dbpsql-tier

services:
  ug.dravom.com:
    container_name: ug.dravom.com
    image: odoo:11.0
    ports:
      - "8069:8069"
    tty: true
    command: -- --dev=reload
#    command: odoo scaffold /mnt/extra-addons/test_module
    environment:
      - VIRTUAL_PORT=8069
#     - HTTPS_METHOD=nohttps
      - VIRTUAL_HOST=ug.dravom.com, dravom.com, www.dravom.com
      - LETSENCRYPT_HOST=ug.dravom.com, dravom.com, www.dravom.com
      - LETSENCRYPT_EMAIL=milda.dvorak@gmail.com
      - HOST=dbpsql
      - USER=odoo
      - PASSWORD=odoo
    hostname: ug.dravom.com
    domainname: dravom.com
    volumes:
      - /data/odoo/odoo_ug_docker/o_addons:/mnt/extra-addons
      - /data/odoo/odoo_ug_docker/o_etc:/etc/odoo
    networks:
      - dbpsql-tier
      - default
